# Generated by Django 4.2.2 on 2023-06-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.CharField(choices=[('groceries', 'Groceries'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('travel', 'Travel'), ('dining', 'Dining'), ('shopping', 'Shopping'), ('housing', 'Housing'), ('transportation', 'Transportation'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('insurance', 'Insurance'), ('debt', 'Debt'), ('subscriptions', 'Subscriptions'), ('personal care', 'Personal Care'), ('gifts', 'Gifts'), ('charity', 'Charity'), ('savings', 'Savings'), ('investments', 'Investments'), ('other', 'Other')], max_length=200),
        ),
    ]
